name: Publish to VSCE

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - name: Publish to VSCE
        run: npm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
