name: Publish to VSCE

on:
  push:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '25'
          cache: 'npm'

      - run: npm ci

      - name: Set up Git
        run: |
          git config --global user.name "John Murowaniecki"
          git config --global user.email "jmurowaniecki@gmail.com"

      - name: Publish to VSCE
        run: npm run publish:dry
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}